create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, username text unique not null check(username ~ '^[a-z0-9_-]{3,24}$'), display_name text not null, bio text default '', avatar_url text, shop_enabled boolean not null default false, created_at timestamptz default now());
create table public.links(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,profile_username text not null, label text not null,url text not null,visible boolean default true,sort int default 0);
create table public.products(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,name text not null,description text default '',price bigint not null check(price>=0),image_url text,visible boolean default true,created_at timestamptz default now());
create table public.orders(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id),feature text not null,amount bigint not null,code text unique not null,status text not null default 'pending' check(status in ('pending','paid','cancelled')),transaction_id text unique,created_at timestamptz default now(),paid_at timestamptz);
alter table profiles enable row level security; alter table links enable row level security; alter table products enable row level security; alter table orders enable row level security;
create policy "public profiles" on profiles for select using(true); create policy "own profile" on profiles for update using(auth.uid()=id);
create policy "public links" on links for select using(visible=true or auth.uid()=user_id); create policy "own links insert" on links for insert with check(auth.uid()=user_id); create policy "own links update" on links for update using(auth.uid()=user_id); create policy "own links delete" on links for delete using(auth.uid()=user_id);
create policy "public products" on products for select using(visible=true or auth.uid()=user_id); create policy "shop product insert" on products for insert with check(auth.uid()=user_id and exists(select 1 from profiles p where p.id=auth.uid() and p.shop_enabled)); create policy "own products update" on products for update using(auth.uid()=user_id); create policy "own products delete" on products for delete using(auth.uid()=user_id);
create policy "own orders read" on orders for select using(auth.uid()=user_id); create policy "own orders insert" on orders for insert with check(auth.uid()=user_id);
