'use client';
import {createBrowserClient} from '@supabase/ssr';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';

type Profile={id:string;username:string;display_name:string;bio:string|null;avatar_url:string|null;shop_enabled:boolean;status_text?:string|null;music_title?:string|null;music_artist?:string|null;music_url?:string|null;music_cover_url?:string|null;bank_name?:string|null;bank_account?:string|null;bank_holder?:string|null;qr_url?:string|null};
type LinkRow={id:number;label:string;url:string;visible:boolean;sort:number};
type Product={id:number;name:string;description:string;price:number;image_url:string|null;visible:boolean};
const socialNames=['Threads','TikTok','Facebook','Instagram','YouTube','Zalo','Discord','GitHub'];
export default function Editor({profile,initialLinks,initialProducts}:{profile:Profile;initialLinks:LinkRow[];initialProducts:Product[]}){
 const router=useRouter(); const supabase=useMemo(()=>createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!),[]);
 const [p,setP]=useState(profile); const [links,setLinks]=useState(initialLinks); const [products,setProducts]=useState(initialProducts); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 const val=(k:keyof Profile)=>(p[k]??'') as string; const change=(k:keyof Profile,v:string)=>setP(x=>({...x,[k]:v}));
 async function saveProfile(){setBusy(true);setMsg('');const {error}=await supabase.from('profiles').update({display_name:p.display_name,bio:p.bio,avatar_url:p.avatar_url,status_text:p.status_text,music_title:p.music_title,music_artist:p.music_artist,music_url:p.music_url,music_cover_url:p.music_cover_url,bank_name:p.bank_name,bank_account:p.bank_account,bank_holder:p.bank_holder,qr_url:p.qr_url}).eq('id',p.id);setBusy(false);setMsg(error?error.message:'✓ Đã lưu Bio');router.refresh()}
 async function upload(file:File,kind:'avatar'|'qr'|'product'|'music'|'musicCover',productId?:number){setBusy(true);const ext=file.name.split('.').pop()||'jpg';const path=`${p.id}/${kind}-${productId||'main'}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('bio-media').upload(path,file,{upsert:true});if(error){setMsg(error.message);setBusy(false);return}const {data}=supabase.storage.from('bio-media').getPublicUrl(path);if(kind==='avatar')setP(x=>({...x,avatar_url:data.publicUrl}));if(kind==='qr')setP(x=>({...x,qr_url:data.publicUrl}));if(kind==='music')setP(x=>({...x,music_url:data.publicUrl}));if(kind==='musicCover')setP(x=>({...x,music_cover_url:data.publicUrl}));if(kind==='product'&&productId){await supabase.from('products').update({image_url:data.publicUrl}).eq('id',productId);setProducts(x=>x.map(y=>y.id===productId?{...y,image_url:data.publicUrl}:y))}setBusy(false);setMsg('✓ Đã tải ảnh. Bấm Lưu thay đổi nếu là Avatar/QR.')}
 async function saveLink(x:LinkRow){const {error}=await supabase.from('links').update({label:x.label,url:x.url,visible:x.visible,sort:x.sort}).eq('id',x.id);setMsg(error?error.message:'✓ Đã lưu liên kết')}
 async function addSocial(){const used=new Set(links.map(x=>x.label));const label=socialNames.find(x=>!used.has(x))||'Website';const {data,error}=await supabase.from('links').insert({user_id:p.id,profile_username:p.username,label,url:'https://',visible:true,sort:links.length}).select().single();if(data)setLinks(x=>[...x,data]);setMsg(error?error.message:'✓ Đã thêm')}
 async function delLink(id:number){await supabase.from('links').delete().eq('id',id);setLinks(x=>x.filter(y=>y.id!==id))}
 async function addProduct(){if(!p.shop_enabled)return;const {data,error}=await supabase.from('products').insert({user_id:p.id,name:'Sản phẩm mới',description:'',price:0,visible:true}).select().single();if(data)setProducts(x=>[...x,data]);setMsg(error?error.message:'✓ Đã thêm sản phẩm')}
 async function saveProduct(x:Product){const {error}=await supabase.from('products').update({name:x.name,description:x.description,price:Number(x.price),image_url:x.image_url,visible:x.visible}).eq('id',x.id);setMsg(error?error.message:'✓ Đã lưu sản phẩm')}
 async function delProduct(id:number){await supabase.from('products').delete().eq('id',id);setProducts(x=>x.filter(y=>y.id!==id))}
 return <div className="editorGrid"><div>
  <section className="card editorCard"><div className="sectionTitle"><div><span>01</span><h2>Hồ sơ</h2></div><a href={`/${p.username}`} target="_blank">Xem Bio ↗</a></div>
   <div className="avatarEdit">{p.avatar_url?<img src={p.avatar_url} alt="avatar"/>:<div className="avatarFallback">{p.display_name?.slice(0,2).toUpperCase()}</div>}<label className="miniBtn">Đổi avatar<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'avatar')}/></label></div>
   <label>Tên hiển thị<input value={val('display_name')} onChange={e=>change('display_name',e.target.value)}/></label><label>Username<input value={p.username} disabled/></label><label>Giới thiệu<textarea rows={4} value={val('bio')} onChange={e=>change('bio',e.target.value)}/></label><label>Status<input value={val('status_text')} onChange={e=>change('status_text',e.target.value)} placeholder="Đang online · Có thể nhắn mình"/></label>
  </section>
  <section className="card editorCard"><div className="sectionTitle"><div><span>02</span><h2>Mạng xã hội</h2></div><button className="miniBtn" onClick={addSocial}>+ Thêm</button></div>{links.map((x,i)=><div className="editRow" key={x.id}><select value={x.label} onChange={e=>setLinks(a=>a.map(y=>y.id===x.id?{...y,label:e.target.value}:y))}>{[...socialNames,'Website'].map(n=><option key={n}>{n}</option>)}</select><input value={x.url} onChange={e=>setLinks(a=>a.map(y=>y.id===x.id?{...y,url:e.target.value}:y))}/><label className="switchLine"><input type="checkbox" checked={x.visible} onChange={e=>setLinks(a=>a.map(y=>y.id===x.id?{...y,visible:e.target.checked}:y))}/> Hiện</label><button onClick={()=>saveLink({...x,sort:i})}>Lưu</button><button onClick={()=>delLink(x.id)}>×</button></div>)}</section>
  <section className="card editorCard"><div className="sectionTitle"><div><span>03</span><h2>Music Player</h2></div></div><label>Tên bài<input value={val('music_title')} onChange={e=>change('music_title',e.target.value)}/></label><label>Nghệ sĩ<input value={val('music_artist')} onChange={e=>change('music_artist',e.target.value)}/></label><div className="musicUploads"><label className="miniBtn uploadBtn">↑ Tải nhạc từ điện thoại<input hidden type="file" accept="audio/mpeg,audio/mp4,audio/ogg,audio/wav,.mp3,.m4a,.ogg,.wav" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'music')}/></label><label className="miniBtn uploadBtn">▣ Ảnh bìa<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'musicCover')}/></label></div><label>URL file nhạc<input value={val('music_url')} onChange={e=>change('music_url',e.target.value)} placeholder="https://.../song.mp3"/></label>{p.music_cover_url&&<img className="musicCoverPreview" src={p.music_cover_url} alt="Ảnh bìa"/>}<p className="muted">MP3 / M4A / OGG phát trực tiếp ngay trên Bio. Sau khi tải file, bấm Lưu thay đổi.</p></section>
  <section className="card editorCard"><div className="sectionTitle"><div><span>04</span><h2>Thanh toán</h2></div></div><label>Ngân hàng<input value={val('bank_name')} onChange={e=>change('bank_name',e.target.value)}/></label><label>Số tài khoản<input value={val('bank_account')} onChange={e=>change('bank_account',e.target.value)}/></label><label>Chủ tài khoản<input value={val('bank_holder')} onChange={e=>change('bank_holder',e.target.value)}/></label><label className="miniBtn uploadBtn">Tải QR từ điện thoại<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'qr')}/></label>{p.qr_url&&<img className="qrPreview" src={p.qr_url} alt="QR"/>}</section>
  <button className="saveAll" disabled={busy} onClick={saveProfile}>{busy?'Đang xử lý...':'Lưu thay đổi'}</button>{msg&&<p className="saveMsg">{msg}</p>}
 </div><aside>
  <section className="card editorCard sticky"><div className="sectionTitle"><div><span>05</span><h2>Shop</h2></div><b className={p.shop_enabled?'enabled':'locked'}>{p.shop_enabled?'ĐÃ MỞ':'KHÓA'}</b></div>{!p.shop_enabled?<><div className="shopPrice">50.000đ</div><p className="muted">Mở khóa một lần cho tài khoản.</p><form action="/api/orders/shop" method="post"><button className="saveAll">Mở khóa Shop</button></form></>:<><button className="miniBtn" onClick={addProduct}>+ Sản phẩm</button>{products.map(x=><div className="productEdit" key={x.id}>{x.image_url&&<img src={x.image_url} alt=""/>}<label className="tinyUpload">Ảnh<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'product',x.id)}/></label><input value={x.name} onChange={e=>setProducts(a=>a.map(y=>y.id===x.id?{...y,name:e.target.value}:y))}/><textarea value={x.description} onChange={e=>setProducts(a=>a.map(y=>y.id===x.id?{...y,description:e.target.value}:y))}/><input type="number" value={x.price} onChange={e=>setProducts(a=>a.map(y=>y.id===x.id?{...y,price:Number(e.target.value)}:y))}/><div className="rowBtns"><label><input type="checkbox" checked={x.visible} onChange={e=>setProducts(a=>a.map(y=>y.id===x.id?{...y,visible:e.target.checked}:y))}/> Hiện</label><button onClick={()=>saveProduct(x)}>Lưu</button><button onClick={()=>delProduct(x.id)}>Xóa</button></div></div>)}</>}</section>
 </aside></div>
}
